sudo: false  # Use container-based infrastructure

language: node_js

os:
  - "linux"
  - "windows"
  - "osx"

node_js:
  - "10"
  - "12"
  - "13"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: nyc npm test && nyc report --reporter=text-lcov | coveralls
